### ISSUE TITLE
mac Stable Diffusion /bin/sh: transparent-background: command not found

### ISSUE THREAD

**Issue by z77256012** [plemeri/transparent-background#12]
Stable Diffusion has been installed locally transparent-background，But the terminal still shows frame extracted
/bin/sh: transparent-background: command not found
mask created

> 
![image](https://user-images.githubusercontent.com/3898707/234646829-36963cfa-f384-43b0-bdb6-bb79c1375fae.png)
Stable Diffusion Installation path is shown in the figure.

**Comment by plemeri** [comment]
Hello, I'm not familiar with Stable Diffusion but as I know, something related to the `command not found` error usually came from the Environment Variable.

**Comment by z77256012** [comment]
@plemeri > transparent-background
Downloading...
From (uriginal): https://drive.google.com/uc?id=13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY
From (redirected): https://drive.google.com/uc?id=13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY&confirm=t&uuid=c31feaa3-c638-430e-ba39-3bda0b3eed1a
To: /Users/settybo/.transparent-background/latest.pth
100%|████████████████████████████████████████| 368M/368M [00:38<00:00, 9.58MB/s]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/transparent-background", line 8, in <module>
    sys.exit(console())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transparent_background/Remover.py", line 111, in console
    if os.path.isdir(args.source):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by plemeri** [comment]
Please check the usage from readme file. At least you need to provide a image file path for command-line tool something like below.
```bash
$ transparent-background --source test.png
```
