### ISSUE TITLE
ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils'

### ISSUE THREAD

**Issue by DEV-MalletteS** [plemeri/transparent-background#79]
PS E:\transparent-background> transparent-background-gui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\transparent-background-gui.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\transparent_background\__init__.py", line 1, in <module>
    from transparent_background.Remover import Remover, console
  File "C:\Python312\Lib\site-packages\transparent_background\Remover.py", line 15, in <module>
    import albumentations as A
  File "C:\Python312\Lib\site-packages\albumentations\__init__.py", line 6, in <module>
    from .augmentations import *
  File "C:\Python312\Lib\site-packages\albumentations\augmentations\__init__.py", line 1, in <module>
    from .blur.functional import *
  File "C:\Python312\Lib\site-packages\albumentations\augmentations\blur\__init__.py", line 1, in <module>
    from .functional import *
  File "C:\Python312\Lib\site-packages\albumentations\augmentations\blur\functional.py", line 9, in <module>
    from albucore.utils import clipped, maybe_process_in_chunks, preserve_channel_dim
ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils' (C:\Python312\Lib\site-packages\albucore\utils.py)
PS E:\transparent-background>

Python312, you haven't specified which py version you used while building this. <3

**Comment by kamal94** [comment]
This seems to be [a problem with albumentations](https://github.com/albumentations-team/albumentations/issues/1945).
I'm working on a PR to pin the version of albucore.

**Comment by DEV-MalletteS** [comment]
For now, which version do you suggest?

**Comment by kamal94** [comment]
This is my suggestion https://github.com/plemeri/transparent-background/pull/80

You can use it with this command, pulling from a fork i'm using while the PR is approved.
```
pip install --extra-index-url https://download.pytorch.org/whl/cu118 git+https://github.com/kamal94/transparent-background@pin-albucore-version
```

**Comment by DEV-MalletteS** [comment]
You're the best, I can't wait to try this.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DEV-MalletteS** [comment]
No problem thank you very much.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
